name: Release

on:
  push:
    branches: [ release/* ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Install .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    # Restore projects
    - name: Restore projects
      run: dotnet restore

    # Build projects
    - name: Build projects
      run: dotnet build --configuration Release --no-restore

    # Run test projects
    - name: Run test projects
      run: dotnet test SIO-API.sln --configuration Release --no-restore --no-build --verbosity normal -- xunit.parallelizeAssembly=true
      env: 
        SIO_AWS__CREDENTIALS__ACCESSKEY: ${{ secrets.AWS_CREDENTAILS_ACCESSKEY }}
        SIO_AWS__CREDENTIALS__SECRETKEY: ${{ secrets.AWS_CREDENTAILS_SECRETKEY }}
        SIO_GOOGLE__CREDENTIALS__TYPE: ${{ secrets.GOOGLE_CREDENTAILS_TYPE }}
        SIO_GOOGLE__CREDENTIALS__PROJECTID: ${{ secrets.GOOGLE_CREDENTAILS_PROJECTID }}
        SIO_GOOGLE__CREDENTIALS__PRIVATEKEYID: ${{ secrets.GOOGLE_CREDENTAILS_PRIVATEKEYID }}
        SIO_GOOGLE__CREDENTIALS__PRIVATEKEY: ${{ secrets.GOOGLE_CREDENTAILS_PRIVATEKEY }}
        SIO_GOOGLE__CREDENTIALS__CLIENTEMAIL: ${{ secrets.GOOGLE_CREDENTAILS_CLIENTEMAIL }}
        SIO_GOOGLE__CREDENTIALS__CLIENTID: ${{ secrets.GOOGLE_CREDENTAILS_CLIENTID }}
        SIO_GOOGLE__CREDENTIALS__AUTHURI: ${{ secrets.GOOGLE_CREDENTAILS_AUTHURI }}
        SIO_GOOGLE__CREDENTIALS__TOKENURI: ${{ secrets.GOOGLE_CREDENTAILS_TOKENURI }}
        SIO_GOOGLE__CREDENTIALS__AUTHPROVIDERX509CERTURL: ${{ secrets.GOOGLE_CREDENTAILS_AUTHPROVIDERX509CERTURL }}
        SIO_GOOGLE__CREDENTIALS__CLIENTX509CERTURL: ${{ secrets.GOOGLE_CREDENTAILS_CLIENTX509CERTURL }}